name: Generate Snake

on:
  schedule:
    - cron: "0 18 * * *" # Runs at 18:00 UTC daily
  workflow_dispatch: # Allow manual trigger
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake SVG/GIF
        uses: Platane/snk@v3
        with:
          github_user_name: sujanlamichhane
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif?color_snake=#00F700

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
